name: Sample yml file
on: [push]
jobs:
  sample-build:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: node version 
        run: |
          node -v
  sub-job:
    runs-on: ubuntu-latest
    needs: sample-build
    name: job2
    steps:
      - name: job2 step
        shell: bash
        run: |
          echo "Nithesh"