name: Sample yml file

#events that trigger workflow
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: node version 
        run: |
          node -v

  job2:
    runs-on: ubuntu-latest
    needs: sample-build
    name: job2
    steps:
      - name: job2 step1
        id: job2_step1
        shell: bash
        run: |
          echo "Nithesh"
      - name: job2 step2
        id: job2_step2
        
